django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('exo.urls')),
    path('admin/', admin.site.urls),
]

django_project/exo/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

informationsUsers = views.InformationsUsers()

app_name = 'exo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('connexion', informationsUsers.connexion, name='connexion'),
    path('connexion2', informationsUsers.modificationInformationEmail, name='connexion2'),
]


urlpatterns += staticfiles_urlpatterns()

django_project/exo/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    user_name = models.CharField(max_length=200, unique=True)
    user_email = models.CharField(max_length=200)
    user_psw = models.CharField(max_length=200)

    def __str__(self):
        return self.user_name+' '+self.user_email

django_project/exo/forms.py
from django import forms

class UserForm(forms.Form):
    user_name = forms.CharField(max_length=100, label="Nom de l'utilisateur")
    user_psw = forms.CharField(max_length=100, widget=forms.PasswordInput, label='Mot de passe')
    verif = forms.BooleanField(label="Cochez si vous souhaitez créer un utilisateur.", required=False)

django_project/exo/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import TemplateView
import json

from .models import Users
from .forms import UserForm

class IndexView(TemplateView):
    template_name = './exo/index.html'
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = UserForm(self.request.POST or None)
        context['error'] = False
        return context
    

class InformationsUsers():

    def __init__(self):
        super().__init__()

    def connexion(self, request):
        if request.method  == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                user_name = form.cleaned_data['user_name']
                #Check id ?
                if not form.cleaned_data['verif']:
                    #User exist ? 
                    if Users.objects.filter(user_name=user_name, user_psw=form.cleaned_data['user_psw']).exists():
                       return self.connexionVerificationValid(request,user_name)
                    #User not exist
                    else:
                        return self.connexionVerificationInValid(request)
                #no Check ? => Create or get User
                else:
                    return self.connexionWithoutPswValidation(request, user_name, form.cleaned_data['user_psw'])

    def connexionVerificationValid(self, request, user_name):
        print("connexionVerificationValid", user_name)
        user = Users.objects.get(user_name=user_name); user.user_psw = None
        return render(request, './exo/modal.html', {'user': user, 'connexionType': 'Connexion avec vérification de mot de passe'} )
    
    def connexionVerificationInValid(self, request):
        print("connexionVerificationInValid")
        form = UserForm(request.POST or None)
        return render(request, './exo/index.html', {'form': form, 'error': True})
    
    def connexionWithoutPswValidation(self, request, user_name, user_psw):
        print("connexionWithoutPswValidation")
        connexionType = "Connexion sans vérification de mot de passe, "
        #User exist ? 
        if Users.objects.filter(user_name=user_name).exists() :
            #Get user
            user = Users.objects.get(user_name=user_name)
            connexionType += "pas de création d'utilisateur"
        else:
            #create user
            user, created = Users.objects.get_or_create(user_name=user_name, user_psw=user_psw)
            connexionType += "avec création d'utilisateur"
        #On ne transmet pas le psw au font
        user.user_psw = None
        return render(request, './exo/modal.html', {'user': user, 'connexionType': connexionType})

    def modificationInformationEmail(self, request):
        print("modificationInformationEmail")
        if request.method  == 'GET':
            print("DATA: ", request.GET)
            #Check user exist
            if Users.objects.filter(user_name=request.GET['user_name']).exists():
                user = Users.objects.get(user_name=request.GET['user_name'])
                user.user_email = request.GET['user_email']
                user.save()
                return JsonResponse({'user_email': user.user_email, 'fait':True})

django_project/exo/templates/exo/accueil.html
{% extends "./base.html" %}

{% block content %}
    <h1>Accueil</h1>
    <p>{{ connexionType }}</p>
    <div class='container d-flex flex-column justify-content-center align-items-center'>
        <h2>Modifier vos identifiants</h2>
        <label for="user_name">Nom d'utilisateur :</label>
        <input type="text" id="user_name" name="user_name" value="{{ user.user_name }}" disabled>
        <label for="user_psw">Mot de passe :</label>
        <input type="password" id="user_psw" name="user_psw" value="helloWorld" disabled>
        <label for="user_email">e-mail :</label>
        <input type="email" id="user_email" name="user_email" value="{{ user.user_email }}" disabled>

        <button type='button' class="btn bg-danger" data-toggle="modal" data-target="#modalInformations"><h4>Modifier vos identifiants</h4></button>

        {% block modal %}{% endblock %}
    </div>
{% endblock %}

django_project/exo/templates/exo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'exo/styles.css' %}">
    <!-- BootStrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>  
    <title>Exo Django</title>
</head>
<body>

    <div class="page d-flex flex-column justify-content-center align-items-center">
        {% block content %}{% endblock %}
    </div>
    

    <footer></footer>


</body>
</html>

django_project/exo/templates/exo/index.html
{% extends "./base.html" %}

{% block content %}


    <h1>Bienvenue à vous</h1>
    <form action="{% url 'exo:connexion' %}" method='POST' class='container d-flex flex-column justify-content-center align-items-center'>
        {% csrf_token %}
        <h2>Entrez vos identifiants</h2>
        {{ form }}
        {% if error %}
            <p>Utilisateur ou Mot de passe inconnu</p>
        {% endif %}
        <button class="m-1" type='submit'>Connexion</button>
    </form>
    
    
{% endblock %}

django_project/exo/templates/exo/modal.html
{% extends "./accueil.html" %}

{% block modal %}
    <div id="modalInformations" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">Modification de vos informations</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
               
                <label for="user_email_modal">e-mail :</label>
                <input type="email" id="user_email_modal" name="user_email_modal" value="{{ user.user_email }}" placeholder="azerty@alpha.io">
                <p id="verification-modal-email"></p>

            </div>
            <div class="modal-footer">
                <button type="button" onclick='updateEmail()' class="btn btn-primary">Enregistrer</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
    <script>
        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }
        function updateEmail()
        {   
            //Vérifie le format de l'email avant envoi de la données
            if(!isEmail(document.getElementById("user_email_modal").value)){
                document.getElementById("verification-modal-email").innerHTML = "Format attendu : azeerty@xxx.xx";
                document.getElementById("verification-modal-email").style.color = "red";
                return false;
            }
            //Envoie de la donnée au serveur pour update l'email
            $.ajax({
                type: "GET",
                url: "{% url 'exo:connexion2' %}",
                data : {
                        'user_name': "{{user.user_name}}",
                        'user_email': document.getElementById("user_email_modal").value,
                },
                dataType: "json",
                success: function (reponse) {
                    if(reponse['fait']){
                        document.getElementById("verification-modal-email").innerHTML = "Modification effectuée";
                        document.getElementById("verification-modal-email").style.color = "green";
                        document.getElementById("user_email").value = reponse['user_email'];
                    }else{
                        document.getElementById("verification-modal-email").innerHTML = "Modification non effectuée: erreur interne";
                        document.getElementById("verification-modal-email").style.color = "red";
                    }
                }
            })
        }
    </script> 
{% endblock %}